### ISSUE TITLE
can you help me? its suddenly stop when searching loot.

### ISSUE THREAD

**Issue by adhafaiq** [norecha/pokubot#11]
![faiq213](https://cloud.githubusercontent.com/assets/10744976/5942851/57cdfe9e-a755-11e4-9f02-654730583537.png)

**Comment by norecha** [comment]
There should be a bug directory where your .jar is, attach the picture inside it

**Comment by adhafaiq** [comment]
![bad_base_1422459428670](https://cloud.githubusercontent.com/assets/10744976/5943011/47d5d8d0-a756-11e4-8f15-56c0af65c9ed.png)
![bad_base_1422460030680](https://cloud.githubusercontent.com/assets/10744976/5943013/48c6dc44-a756-11e4-9378-1a391b1b9cbb.png)

**Comment by adhafaiq** [comment]
![bad_base_1422459428670](https://cloud.githubusercontent.com/assets/10744976/5943020/54847dac-a756-11e4-90cf-22ea2c90fadc.png)
![bad_base_1422460030680](https://cloud.githubusercontent.com/assets/10744976/5943021/55be0f94-a756-11e4-893f-495a68c51e3a.png)
![bad_base_1422461072226](https://cloud.githubusercontent.com/assets/10744976/5943022/56eaad5a-a756-11e4-9a65-735d428ad584.png)

**Comment by adhafaiq** [comment]
do i have to put the .jar in the pokubot.master?

**Comment by adhafaiq** [comment]
that is the picture sir. help me pls. sorry for interrupting you :(

**Comment by norecha** [comment]
I found the problem, I will need you to test it before I make a new release though. What's your email

**Comment by 4543562a** [comment]
I also have the same issue.  I had the same settings except no match with 180k coins and 0 elixir

[01.28.15 7:58:54 PM] aok.coc.state.StateAttack handle INFO: StateAttack 
[01.28.15 7:58:55 PM] aok.coc.launcher.BotLauncher loop SEVERE: de: ff83782b 
aok.coc.exception.BotBadBaseException: de: ff83782b
	at aok.coc.util.ImageParser.hasDE(ImageParser.java:169)
	at aok.coc.util.ImageParser.parseGold(ImageParser.java:174)
	at aok.coc.util.ImageParser.parseLoot(ImageParser.java:329)
	at aok.coc.state.StateAttack.handle(StateAttack.java:46)
	at aok.coc.state.Context.handle(Context.java:20)
	at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:86)
	at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:154)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:149)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$436(Unknown Source)
	at javafx.concurrent.Service$$Lambda$251/1568401967.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$437(Unknown Source)
	at javafx.concurrent.Service$$Lambda$249/1314905605.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[01.28.15 7:58:55 PM] aok.coc.launcher.BotLauncher loop INFO: Waiting for dc checker to wake me up... 


![bad_base_1422493134938]
(https://cloud.githubusercontent.com/assets/10750133/5950496/e156db2c-a728-11e4-8a6c-67bbca1f90a0.png)
![bad_base_1422493176377](https://cloud.githubusercontent.com/assets/10750133/5950497/e1578d88-a728-11e4-9602-f0ebf8ff388d.png)

**Comment by adhafaiq** [comment]
adha_faiq@yahoo.com this is my email

**Comment by adhafaiq** [comment]
sir can you email me sir? pls

**Comment by norecha** [comment]
@adhafaiq 
I sent you the new version, test it and let me know if there are problems, then I can make a release

**Comment by chicksatan** [comment]
Plz send me the new version cause i have problems like him ... ng.tri67@gmail.com

**Comment by norecha** [comment]
@chicksatan 
sent

**Comment by 4543562a** [comment]
I'd also like to test out this version
4543562a@gmail.com  

thanks

**Comment by hyuda** [comment]
Hi norecha
Ca i get email too because i have same problem with adhafaiq
My email: dk_kurniawan@ymail.com

Thanks

**Comment by chicksatan** [comment]
Thanks u @norecha but version u sent me have problems , it don't auto zooming out and usually disconnect . Plz help me fix it.

**Comment by salimovitch** [comment]
i have the same probleme please help me, email : salimo12@hotmail.fr

**Comment by Tigerwoodz28** [comment]
same problem here master...can you help me please...thankyou...
tigerwoodz28@yahoo.com

**Comment by norecha** [comment]
Try latest release

**Comment by azerool** [comment]
i also got same prob. . . waiting. . . .. 
my email
azerool1976@gmail.com

**Comment by norecha** [comment]
Already fixed in latest release

**Comment by apyapy** [comment]
norecha , Hi thanks for the great project
you are saying that you already fixed that problem but i DO get this error "de: ff83782b" "Waiting for dc checker to wake me up..."

**Comment by norecha** [comment]
what is the version on top right

**Comment by apyapy** [comment]
ver 1.0.2

**Comment by apyapy** [comment]
the bot does work good. until the error appears.. i will sure keep testing it just wanted to let you know.

**Comment by norecha** [comment]
does it happen for every base with DE?
attach the log file pls

**Comment by apyapy** [comment]
[02.02.15 11:15:53 PM] aok.coc.util.ImageParser parseLoot INFO: [gold: 7814, elixir: 7581, de: 68] 
[02.02.15 11:15:53 PM] aok.coc.util.ImageParser parseTroopCount INFO: [Troop count: [208, 12, 0, 1]] 
[02.02.15 11:15:53 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 817 483 
[02.02.15 11:15:56 PM] aok.coc.state.StateAttack handle INFO: StateAttack 
[02.02.15 11:15:56 PM] aok.coc.launcher.BotLauncher loop SEVERE: de: fffbffff 
aok.coc.exception.BotBadBaseException: de: fffbffff
	at aok.coc.util.ImageParser.hasDE(ImageParser.java:171)
	at aok.coc.util.ImageParser.parseGold(ImageParser.java:176)
	at aok.coc.util.ImageParser.parseLoot(ImageParser.java:329)
	at aok.coc.util.ImageParser.parseLoot(ImageParser.java:341)
	at aok.coc.state.StateAttack.handle(StateAttack.java:46)
	at aok.coc.state.Context.handle(Context.java:20)
	at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:86)
	at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:154)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:149)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$436(Unknown Source)
	at javafx.concurrent.Service$$Lambda$251/810586007.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$437(Unknown Source)
	at javafx.concurrent.Service$$Lambda$249/1927497023.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[02.02.15 11:15:56 PM] aok.coc.launcher.BotLauncher loop INFO: Waiting for dc checker to wake me up... 
[02.02.15 11:16:19 PM] aok.coc.controller.MainWindowController$4 handle WARNING: runner is cancelled. 
[02.02.15 11:16:19 PM] aok.coc.launcher.DisconnectChecker run SEVERE: dc checker: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.launcher.DisconnectChecker.run(DisconnectChecker.java:68)
	at java.lang.Thread.run(Unknown Source)

**Comment by apyapy** [comment]
does it helps? as for your question if it only happen with DE base i cannot tell because i didnt pay attention..

**Comment by norecha** [comment]
You said you get de: ff83782b, which I already fixed, but your log file says de: fffbffff .
Attach the pictures in bug folder
