### ISSUE TITLE
Bot sets up and trains barch but wont keep searching after first match

### ISSUE THREAD

**Issue by MAXTroops** [norecha/pokubot#35]
Bot sets up and trains barch but wont keep searching after first match
![screenshot 2015-02-13 10 44 00](https://cloud.githubusercontent.com/assets/10996928/6193232/051bedf8-b36e-11e4-9630-4096c96c444b.png)

**Comment by sitolawrence** [comment]
I have a similar problem but after the second or first match when it returns back to base it's zoomed up and it creates a detection connector and a dc checker. I'm not sure how to fix that

**Comment by norecha** [comment]
add log files

**Comment by MAXTroops** [comment]
Is that just another download that's found on this site and do I need to do anything once I download it place it somewhere. Appreciate the help really want it to work. hear it gets great loot.

**Comment by MAXTroops** [comment]
Is it calleg log files sorry I'm just dumb

**Comment by norecha** [comment]
wherever your downloaded jar is, there should be a file called pokulog.txt
paste that here

**Comment by MAXTroops** [comment]
[02.13.15 10:35:24 AM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils... 
[02.13.15 10:35:29 AM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player window... 
[02.13.15 10:35:55 AM] aok.coc.launcher.Setup setupBsRect FINEST: The corner locations for the window "BlueStacks App Player" are [691, 7, 1557, 755] 
[02.13.15 10:35:55 AM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player resolution... 
[02.13.15 10:35:56 AM] aok.coc.launcher.Setup setup INFO: Setting up RobotUtils... 
[02.13.15 10:35:56 AM] aok.coc.launcher.Setup setup INFO: Setting up Barracks... 
[02.13.15 10:35:56 AM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[02.13.15 10:36:22 AM] org.jnativehook.GlobalScreen loadNativeLibrary WARNING: Invalid library manifest!
 
[02.13.15 10:36:23 AM] aok.coc.launcher.Setup setupBarracks INFO: Waiting for user to click on first barracks. 
[02.13.15 10:36:24 AM] aok.coc.launcher.Setup$1 nativeMouseClicked FINEST: clicked 960 418 
[02.13.15 10:36:25 AM] aok.coc.launcher.Setup setupBarracks INFO: Set barracks location to <266, 386> 
[02.13.15 10:36:25 AM] aok.coc.controller.MainWindowController$7 handle INFO: Setup is successful. 
[02.13.15 10:36:25 AM] aok.coc.controller.MainWindowController$7 handle INFO: Click start to run. 
[02.13.15 10:40:19 AM] aok.coc.util.ConfigUtils save INFO: Settings are saved. 
[02.13.15 10:40:25 AM] aok.coc.launcher.BotLauncher start INFO: Starting disconnect detector... 
[02.13.15 10:40:25 AM] aok.coc.launcher.DisconnectChecker run INFO: Running disconnect detector... 
[02.13.15 10:40:25 AM] aok.coc.state.Context setState FINEST: Setting next state to: StateIdle 
[02.13.15 10:40:25 AM] aok.coc.state.StateIdle handle INFO: StateIdle 
[02.13.15 10:40:26 AM] aok.coc.state.Context setState FINEST: Setting next state to: StateMainMenu 
[02.13.15 10:40:26 AM] aok.coc.state.StateMainMenu handle INFO: StateMainMenu 
[02.13.15 10:40:26 AM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[02.13.15 10:40:41 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 266 386 
[02.13.15 10:40:42 AM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_MAX_TRAIN fff7f5f4 ff7ea33c 
[02.13.15 10:40:42 AM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_TRAIN fff8f4f8 ff000000 
[02.13.15 10:40:42 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 266 386 
[02.13.15 10:40:43 AM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_MAX_TRAIN fff7f5f4 fff7f5f4 
[02.13.15 10:40:43 AM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_TRAIN fff8f4f8 ff000000 
[02.13.15 10:40:43 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 565 583 
[02.13.15 10:40:44 AM] aok.coc.state.StateMainMenu handle INFO: Camp is full 
[02.13.15 10:40:44 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 730 146 
[02.13.15 10:40:44 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 64 599 
[02.13.15 10:40:46 AM] aok.coc.state.Context setState FINEST: Setting next state to: StateFindAMatch 
[02.13.15 10:40:47 AM] aok.coc.state.StateFindAMatch handle INFO: StateFindAMatch 
[02.13.15 10:40:47 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 148 530 
[02.13.15 10:40:47 AM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 512 397

**Comment by norecha** [comment]
It cannot detect your next button. Are you using bot like in screenshot? Whole screen must be visible, there is no background mode

**Comment by roinoir** [comment]
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils... 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Make sure in-game language is English. 
[03.05.15 4:03:36 PM] aok.coc.util.ConfigUtils initialize INFO: Found barracks coordinates <335, 462> 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player window... 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setupBsRect FINEST: The corner locations for the window "BlueStacks App Player" are [20, 20, 886, 768] 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player resolution... 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Setting up RobotUtils... 
[03.05.15 4:03:36 PM] aok.coc.launcher.Setup setup INFO: Setting up Barracks... 
[03.05.15 4:03:36 PM] aok.coc.controller.MainWindowController$7 handle INFO: Setup is successful. 
[03.05.15 4:03:36 PM] aok.coc.controller.MainWindowController$7 handle INFO: Click start to run. 
[03.05.15 4:03:49 PM] aok.coc.launcher.BotLauncher start INFO: Starting disconnect detector... 
[03.05.15 4:03:49 PM] aok.coc.launcher.DisconnectChecker run INFO: Running disconnect detector... 
[03.05.15 4:03:49 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateIdle 
[03.05.15 4:03:49 PM] aok.coc.state.StateIdle handle INFO: StateIdle 
[03.05.15 4:03:49 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateMainMenu 
[03.05.15 4:03:49 PM] aok.coc.state.StateMainMenu handle INFO: StateMainMenu 
[03.05.15 4:03:49 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[03.05.15 4:04:04 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 335 462 
[03.05.15 4:04:05 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 572 592 
[03.05.15 4:04:06 PM] aok.coc.state.StateMainMenu handle INFO: Camp is full 
[03.05.15 4:04:06 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 730 145 
[03.05.15 4:04:06 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 63 599 
[03.05.15 4:04:08 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateFindAMatch 
[03.05.15 4:04:09 PM] aok.coc.state.StateFindAMatch handle INFO: StateFindAMatch 
[03.05.15 4:04:09 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 149 528 
[03.05.15 4:04:09 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 511 396 
[03.05.15 4:07:56 PM] aok.coc.controller.MainWindowController$4 handle WARNING: runner is cancelled. 
[03.05.15 4:07:56 PM] aok.coc.launcher.BotLauncher loop INFO: Interrupted by user. 
[03.05.15 4:07:56 PM] aok.coc.launcher.DisconnectChecker run SEVERE: dc checker: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.launcher.DisconnectChecker.run(DisconnectChecker.java:68)
	at java.lang.Thread.run(Unknown Source)

same log has him
all bluestacks is visible (no screen hiden like the picture above)

**Comment by norecha** [comment]
your game is english?

**Comment by roinoir** [comment]
it wasn't forgot that side now it is and work perfectly like promise il donate to you :)
