### ISSUE TITLE
Bot Stop after find match/ StateAttack

### ISSUE THREAD

**Issue by larknart** [norecha/pokubot#36]
i tried on my other computer, windows 7 pro sp1 32bit...bot run perfectly on zoom out, train troop but stop after click find a match.

BS resolution: checked
CoC language: english 
pokubot: 1.0.2 (latest version on release)

logs:
[02.15.15 2:10:19 PM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils... 
[02.15.15 2:10:19 PM] aok.coc.util.ConfigUtils initialize INFO: Found barracks coordinates <589, 393> 
[02.15.15 2:10:19 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player window... 
[02.15.15 2:10:21 PM] aok.coc.launcher.Setup setupBsRect FINEST: The corner locations for the window "BlueStacks App Player" are [9, 10, 875, 758] 
[02.15.15 2:10:21 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player resolution... 
[02.15.15 2:10:21 PM] aok.coc.launcher.Setup setup INFO: Setting up RobotUtils... 
[02.15.15 2:10:21 PM] aok.coc.launcher.Setup setup INFO: Setting up Barracks... 
[02.15.15 2:10:21 PM] aok.coc.controller.MainWindowController$7 handle INFO: Setup is successful. 
[02.15.15 2:10:21 PM] aok.coc.controller.MainWindowController$7 handle INFO: Click start to run. 
[02.15.15 2:10:30 PM] aok.coc.launcher.BotLauncher start INFO: Starting disconnect detector... 
[02.15.15 2:10:30 PM] aok.coc.launcher.DisconnectChecker run INFO: Running disconnect detector... 
[02.15.15 2:10:31 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateIdle 
[02.15.15 2:10:31 PM] aok.coc.state.StateIdle handle INFO: StateIdle 
[02.15.15 2:10:31 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateMainMenu 
[02.15.15 2:10:31 PM] aok.coc.state.StateMainMenu handle INFO: StateMainMenu 
[02.15.15 2:10:31 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[02.15.15 2:10:46 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 589 393 
[02.15.15 2:10:47 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_MAX_TRAIN fff7f5f4 ffcdcfcc 
[02.15.15 2:10:47 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClickableActive: BUTTON_RAX_TRAIN fff8f4f8 fff8f4f8 
[02.15.15 2:10:47 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 615 585 
[02.15.15 2:10:48 PM] aok.coc.state.StateMainMenu handle INFO: Camp is full 
[02.15.15 2:10:48 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 729 144 
[02.15.15 2:10:48 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 63 599 
[02.15.15 2:10:49 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateFindAMatch 
[02.15.15 2:10:50 PM] aok.coc.state.StateFindAMatch handle INFO: StateFindAMatch 
[02.15.15 2:10:50 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 148 530 
[02.15.15 2:10:50 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 511 396 
[02.15.15 2:10:55 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateAttack 
[02.15.15 2:10:55 PM] aok.coc.state.StateAttack handle INFO: StateAttack 
[02.15.15 2:10:55 PM] aok.coc.util.ImageParser parseLoot INFO: [gold: 356053, elixir: 354378, de: 1356] 
[02.15.15 2:10:57 PM] aok.coc.controller.MainWindowController$5 handle SEVERE: runner is failed. 
[02.15.15 2:10:57 PM] aok.coc.launcher.DisconnectChecker run SEVERE: dc checker: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.launcher.DisconnectChecker.run(DisconnectChecker.java:68)
	at java.lang.Thread.run(Unknown Source)

**Comment by norecha** [comment]
You must be getting an Error parsing your troops but it doesn't show in the log.
Can you run it from command line like this:
C:\programfiles\....your_java_dir\bin\java.exe -jar C:\your_jar_dir\pokubot-v1.x.x.jar

**Comment by mannguyen0107** [comment]
hi poku i want to ask what software did you use to dev the bot i would like to poke around and see if i can do anything

**Comment by norecha** [comment]
Software? I didn't use any software, I coded in java which is already open source

**Comment by mannguyen0107** [comment]
oh well there is a Autoit script that have alot of features that urs dont have i wonder if you want to take a look into that perhaps i can send you the link :D

**Comment by larknart** [comment]
hmmm...before i run with those command line, i tried to update my intels display driver..then got error on barrack locate..

C:\Program Files\Java\jre1.8.0_31\bin>java.exe -jar C:\pokubot\pokubot-1.0.2.jar

[02.17.15 1:11:44 PM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils.
..
[02.17.15 1:11:44 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks A
pp Player window...
[02.17.15 1:11:45 PM] aok.coc.launcher.Setup setupBsRect FINEST: The corner loca
tions for the window "BlueStacks App Player" are [20, 20, 886, 768]
[02.17.15 1:11:45 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks A
pp Player resolution...
[02.17.15 1:11:45 PM] aok.coc.launcher.Setup setup INFO: Setting up RobotUtils..
.
[02.17.15 1:11:45 PM] aok.coc.launcher.Setup setup INFO: Setting up Barracks...

[02.17.15 1:11:45 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out...
[02.17.15 1:12:08 PM] org.jnativehook.GlobalScreen loadNativeLibrary WARNING: In
valid library manifest!


JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2014 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

[02.17.15 1:12:08 PM] aok.coc.launcher.Setup setupBarracks INFO: Waiting for use
r to click on first barracks.
[02.17.15 1:12:14 PM] aok.coc.launcher.Setup$1 nativeMouseClicked FINEST: clicke
d 556 292
[02.17.15 1:12:14 PM] aok.coc.launcher.Setup setupBarracks INFO: Set barracks lo
cation to <533, 247>
[02.17.15 1:12:14 PM] aok.coc.controller.MainWindowController$7 handle INFO: Set
up is successful.
[02.17.15 1:12:14 PM] aok.coc.controller.MainWindowController$7 handle INFO: Cli
ck start to run.
[02.17.15 1:12:21 PM] aok.coc.launcher.BotLauncher start INFO: Starting disconne
ct detector...
[02.17.15 1:12:21 PM] aok.coc.launcher.DisconnectChecker run INFO: Running disco
nnect detector...
[02.17.15 1:12:21 PM] aok.coc.state.Context setState FINEST: Setting next state
to: StateIdle
[02.17.15 1:12:21 PM] aok.coc.state.StateIdle handle INFO: StateIdle
[02.17.15 1:12:21 PM] aok.coc.state.Context setState FINEST: Setting next state
to: StateMainMenu
[02.17.15 1:12:21 PM] aok.coc.state.StateMainMenu handle INFO: StateMainMenu
[02.17.15 1:12:21 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out...
[02.17.15 1:12:36 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 53
3 247
[02.17.15 1:12:36 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClicka
bleActive: BUTTON_RAX_MAX_TRAIN fff7f5f4 ff7ea33c
[02.17.15 1:12:37 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClicka
bleActive: BUTTON_RAX_TRAIN fff8f4f8 ffa3c34a
[02.17.15 1:12:37 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 53
3 247
[02.17.15 1:12:37 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClicka
bleActive: BUTTON_RAX_MAX_TRAIN fff7f5f4 ffcdcfcc
[02.17.15 1:12:37 PM] aok.coc.util.RobotUtils isClickableActive FINEST: isClicka
bleActive: BUTTON_RAX_TRAIN fff8f4f8 ffa3c34a
[02.17.15 1:12:37 PM] aok.coc.state.StateMainMenu handle SEVERE: Unable to locat
e barracks.
[02.17.15 1:12:37 PM] aok.coc.launcher.BotLauncher loop SEVERE: Barracks locatio
n is not correct.
aok.coc.exception.BotConfigurationException: Barracks location is not correct.
        at aok.coc.state.StateMainMenu.handle(StateMainMenu.java:39)
        at aok.coc.state.Context.handle(Context.java:20)
        at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:86)
        at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
        at aok.coc.controller.MainWindowController$3$1.call(MainWindowController
.java:154)
        at aok.coc.controller.MainWindowController$3$1.call(MainWindowController
.java:149)
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.concurrent.Service.lambda$null$436(Unknown Source)
        at javafx.concurrent.Service$$Lambda$251/12539974.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at javafx.concurrent.Service.lambda$executeTask$437(Unknown Source)
        at javafx.concurrent.Service$$Lambda$249/25841854.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

[02.17.15 1:12:37 PM] aok.coc.launcher.BotLauncher loop INFO: Waiting for dc che
cker to wake me up...

**Comment by norecha** [comment]
did you move or boost your barracks?
