### ISSUE TITLE
StateIdle

### ISSUE THREAD

**Issue by AomineDaiki21** [norecha/pokubot#38]
[02.18.15 6:44:27 PM] aok.coc.controller.MainWindowController$8 handle GRAVE: Setup is failed. 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setup INFORMAZIONI: Setting up ConfigUtils... 
[02.18.15 6:44:53 PM] aok.coc.util.ConfigUtils initialize INFORMAZIONI: Found barracks coordinates <244, 241> 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setup INFORMAZIONI: Setting up BlueStacks App Player window... 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setupBsRect OTTIMALE: The corner locations for the window "BlueStacks App Player" are [20, 20, 886, 768] 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setup INFORMAZIONI: Setting up BlueStacks App Player resolution... 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setup INFORMAZIONI: Setting up RobotUtils... 
[02.18.15 6:44:53 PM] aok.coc.launcher.Setup setup INFORMAZIONI: Setting up Barracks... 
[02.18.15 6:44:53 PM] aok.coc.controller.MainWindowController$7 handle INFORMAZIONI: Setup is successful. 
[02.18.15 6:44:53 PM] aok.coc.controller.MainWindowController$7 handle INFORMAZIONI: Click start to run. 
[02.18.15 6:46:32 PM] aok.coc.launcher.BotLauncher start INFORMAZIONI: Starting disconnect detector... 
[02.18.15 6:46:32 PM] aok.coc.state.Context setState OTTIMALE: Setting next state to: StateIdle 
[02.18.15 6:46:32 PM] aok.coc.launcher.DisconnectChecker run INFORMAZIONI: Running disconnect detector... 
[02.18.15 6:46:32 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:33 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:34 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:35 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:37 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:38 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:39 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:40 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:41 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:42 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:43 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:44 PM] aok.coc.state.StateIdle handle INFORMAZIONI: StateIdle 
[02.18.15 6:46:45 PM] aok.coc.controller.MainWindowController$4 handle AVVERTENZA: runner is cancelled. 
[02.18.15 6:46:45 PM] aok.coc.launcher.BotLauncher loop INFORMAZIONI: Interrupted by user. 
[02.18.15 6:46:45 PM] aok.coc.launcher.DisconnectChecker run GRAVE: dc checker: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.launcher.DisconnectChecker.run(DisconnectChecker.java:68)
	at java.lang.Thread.run(Unknown Source)

[02.18.15 6:46:45 PM] aok.coc.controller.MainWindowController$3$1 call GRAVE: runner: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.state.StateIdle.handle(StateIdle.java:48)
	at aok.coc.state.Context.handle(Context.java:20)
	at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:86)
	at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:154)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:149)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$436(Unknown Source)
	at javafx.concurrent.Service$$Lambda$251/23368882.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$437(Unknown Source)
	at javafx.concurrent.Service$$Lambda$249/21652539.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

My resolution is 860x720 but i still got the "statidle porblem", after i press start nothing happens

**Comment by roinoir** [comment]
game is in english ?

**Comment by motodemoemail** [comment]
I am having this very same issue. Running Win 7 64 bit and Java version 8 update 40 (Newest version). I am new to this, so I installed Bluestacks yesterday, and the Pokubot newest version, but still continue to have the same issue. I made the changes in the registry as well. Game is in English as well.

**Comment by motodemoemail** [comment]
UPDATE: I fixed this by updating my NVidia Video Card drivers for my GTX 760.
