### ISSUE TITLE
Bot worked but now stuck on cant find dependant libraries

### ISSUE THREAD

**Issue by badboy1645** [norecha/pokubot#43]
Hi, Great program and id like to contribute but sometimes it works and now it doesnt work at all, its stuck on dependant libraries, ive removed and re installed everything associated, bluestacks, the bot program, java etc, any help would be appreciated, thanks.

log file here

[02.26.15 11:15:05 PM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils... 
[02.26.15 11:15:05 PM] aok.coc.launcher.Setup setup INFO: Make sure in-game language is English. 
[02.26.15 11:15:05 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player window... 
[02.26.15 11:15:06 PM] aok.coc.launcher.Setup setupBsRect FINEST: The corner locations for the window "BlueStacks App Player" are [715, 30, 1581, 775] 
[02.26.15 11:15:06 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player resolution... 
[02.26.15 11:15:06 PM] aok.coc.launcher.Setup setup INFO: Setting up RobotUtils... 
[02.26.15 11:15:06 PM] aok.coc.launcher.Setup setup INFO: Setting up Barracks... 
[02.26.15 11:15:06 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[02.26.15 11:15:48 PM] org.jnativehook.GlobalScreen loadNativeLibrary WARNING: Invalid library manifest!
 
[02.26.15 11:15:48 PM] aok.coc.launcher.Setup setupBarracks INFO: Waiting for user to click on first barracks. 
[02.26.15 11:15:52 PM] aok.coc.launcher.Setup$1 nativeMouseClicked FINEST: clicked 1095 546 
[02.26.15 11:15:52 PM] aok.coc.launcher.Setup setupBarracks INFO: Set barracks location to <377, 494> 
[02.26.15 11:15:52 PM] aok.coc.controller.MainWindowController$7 handle INFO: Setup is successful. 
[02.26.15 11:15:52 PM] aok.coc.controller.MainWindowController$7 handle INFO: Click start to run. 
[02.26.15 11:16:22 PM] aok.coc.util.ConfigUtils save INFO: Settings are saved. 
[02.26.15 11:16:27 PM] aok.coc.launcher.BotLauncher start INFO: Starting disconnect detector... 
[02.26.15 11:16:27 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateIdle 
[02.26.15 11:16:27 PM] aok.coc.state.StateIdle handle INFO: StateIdle 
[02.26.15 11:16:27 PM] aok.coc.launcher.DisconnectChecker run INFO: Running disconnect detector... 
[02.26.15 11:16:27 PM] aok.coc.state.Context setState FINEST: Setting next state to: StateMainMenu 
[02.26.15 11:16:27 PM] aok.coc.state.StateMainMenu handle INFO: StateMainMenu 
[02.26.15 11:16:27 PM] aok.coc.util.RobotUtils zoomUp INFO: Zooming out... 
[02.26.15 11:16:42 PM] aok.coc.util.RobotUtils leftClickWin32 FINEST: clicking 377 494 
[02.26.15 11:16:43 PM] aok.coc.launcher.DisconnectChecker run SEVERE: dc checker: sleep interrupted 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at aok.coc.launcher.DisconnectChecker.run(DisconnectChecker.java:68)
	at java.lang.Thread.run(Unknown Source)

[02.26.15 11:16:43 PM] aok.coc.controller.MainWindowController$5 handle SEVERE: runner is failed: C:\Users\Bigboy\AppData\Local\Temp\javacpp1290261354026\jniopencv_core.dll: Can't find dependent libraries 
java.lang.UnsatisfiedLinkError: C:\Users\Bigboy\AppData\Local\Temp\javacpp1290261354026\jniopencv_core.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:418)
	at com.googlecode.javacpp.Loader.load(Loader.java:368)
	at com.googlecode.javacpp.Loader.load(Loader.java:315)
	at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:131)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.googlecode.javacpp.Loader.load(Loader.java:334)
	at com.googlecode.javacpp.Loader.load(Loader.java:315)
	at com.googlecode.javacv.cpp.opencv_core$CvArr.<clinit>(opencv_core.java:158)
	at org.sikuli.core.cv.ImagePreprocessor.createGrayscale(ImagePreprocessor.java:52)
	at org.sikuli.core.search.algorithm.TemplateMatcher.findMatchesByGrayscaleAtOriginalResolution(TemplateMatcher.java:18)
	at aok.coc.util.ImageParser.findArea(ImageParser.java:290)
	at aok.coc.util.ImageParser.findTrainButton(ImageParser.java:270)
	at aok.coc.state.StateMainMenu.handle(StateMainMenu.java:30)
	at aok.coc.state.Context.handle(Context.java:20)
	at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:86)
	at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:153)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:149)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$436(Unknown Source)
	at javafx.concurrent.Service$$Lambda$250/13374597.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$437(Unknown Source)
	at javafx.concurrent.Service$$Lambda$248/7204212.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by norecha** [comment]
Try running in admin mode and lmk

**Comment by badboy1645** [comment]
Hi, Thanks for the prompt reply, I am logged in as administrator and as far as i can tell i have the correct java installed im running 32 bit vista and the java is version 8 update 31 (build 1.8.0_31-b13) ive run the java applet and it says its correct??

**Comment by badboy1645** [comment]
hello again, just to recap, any other ideas? thanks for your help

**Comment by badboy1645** [comment]
Hi, I was wondering if you had any other ideas, or shall i just delete the program and forget about it?

**Comment by norecha** [comment]
I have no idea why you are getting that. It is trying to extract that file to temp folder but cannot do it for some reason. When you get that error check if jniopencv_core.dll is actually there

**Comment by badboy1645** [comment]
Hi, I  did a bit of digging on the net and found this, which has cured the problem...

http://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

If anyone else has exactly the same issue, download and install visual c++
