### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by roinoir** [norecha/pokubot#45]
[03.04.15 6:30:30 PM] INFO: Setting up ConfigUtils... 
[03.04.15 6:30:30 PM] INFO: Make sure in-game language is English. 
[03.04.15 6:30:30 PM] INFO: Setting up BlueStacks App Player window... 
[03.04.15 6:30:30 PM] INFO: Setting up BlueStacks App Player resolution... 
[03.04.15 6:30:30 PM] SEVERE: Setup is failed: Unable to change resolution. Do it manually. 

i have already read the instruction and change the resolution manually to 860/720

i don't have any luck i supose x)

BS version 0.8.10.3096 (last update 2015-03-04)
using jave 8 version jre1.8.0_40 (launched by javaw)
OS windows 7 sp1

**Comment by roinoir** [comment]
il be more than happy to donate to your hard work if you help me to make it run

all setting are placed like you write it on ur read me

resolution is changed in regedit 

(saw on internet it was guessheight and guesswidth but on mine is only height and width no guess before)

**Comment by norecha** [comment]
Put the log file

**Comment by roinoir** [comment]
[03.05.15 2:43:34 PM] aok.coc.launcher.Setup setup INFO: Setting up ConfigUtils... 
[03.05.15 2:43:34 PM] aok.coc.launcher.Setup setup INFO: Make sure in-game language is English. 
[03.05.15 2:43:34 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player window... 
[03.05.15 2:43:34 PM] aok.coc.launcher.Setup setupBsRect FINEST: The corner locations for the window "BlueStacks App Player" are [143, 8, 1278, 982] 
[03.05.15 2:43:34 PM] aok.coc.launcher.Setup setup INFO: Setting up BlueStacks App Player resolution... 
[03.05.15 2:43:34 PM] aok.coc.controller.MainWindowController$8 handle SEVERE: Setup is failed: Unable to change resolution. Do it manually. 
aok.coc.exception.BotConfigurationException: Unable to change resolution. Do it manually.
	at aok.coc.launcher.Setup.setupResolution(Setup.java:215)
	at aok.coc.launcher.Setup.setup(Setup.java:58)
	at aok.coc.launcher.BotLauncher.setup(BotLauncher.java:52)
	at aok.coc.controller.MainWindowController$6$1.call(MainWindowController.java:189)
	at aok.coc.controller.MainWindowController$6$1.call(MainWindowController.java:184)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$488(Unknown Source)
	at javafx.concurrent.Service$$Lambda$265/1244546692.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$489(Unknown Source)
	at javafx.concurrent.Service$$Lambda$263/927114246.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.sun.jna.platform.win32.Win32Exception: Le fichier spécifié est introuvable.
	at com.sun.jna.platform.win32.Advapi32Util.registryGetIntValue(Advapi32Util.java:837)
	at aok.coc.launcher.Setup.setupResolution(Setup.java:172)
	... 14 more

**Comment by norecha** [comment]
Add missing ones to registry.
It should have:

WindowWidth
WindowHeight
GuestWidth
GuestHeight

**Comment by roinoir** [comment]
what value does it give to them ?

**Comment by roinoir** [comment]
norecha

reinstalling Bluestacks seems to work (you should add it in your read me file)
im doing last check up to see if all work

:)

**Comment by norecha** [comment]
860 for width 720 for height.

it works because you added missing 2

**Comment by roinoir** [comment]
nah i completly reinstalled it and remove all key from register (BS one)
they add good one and its automaticly set to good resolution
