### ISSUE TITLE
[Issue] Could not parse any number at 33 0

### ISSUE THREAD

**Issue by ashishmverma1** [norecha/pokubot#74]
Bot's working great after the update! Just encountered this issue once:
<code>Could not parse any number at 33 0</code>

Log:
<pre>
[07.04.15 1:30:45 AM] aok.coc.state.StateAttack handle INFO: StateAttack 
[07.04.15 1:30:46 AM] aok.coc.launcher.BotLauncher loop SEVERE: Could not parse any number at 33 0 
aok.coc.exception.BotBadBaseException: Could not parse any number at 33 0
	at aok.coc.util.ImageParser.parseNumberFromBinary(ImageParser.java:252)
	at aok.coc.util.ImageParser.parseGoldFromBinary(ImageParser.java:74)
	at aok.coc.util.ImageParser.parseLoot(ImageParser.java:302)
	at aok.coc.util.ImageParser.parseLoot(ImageParser.java:324)
	at aok.coc.state.StateAttack.handle(StateAttack.java:45)
	at aok.coc.state.Context.handle(Context.java:20)
	at aok.coc.launcher.BotLauncher.loop(BotLauncher.java:88)
	at aok.coc.launcher.BotLauncher.start(BotLauncher.java:72)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:154)
	at aok.coc.controller.MainWindowController$3$1.call(MainWindowController.java:150)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$488(Unknown Source)
	at javafx.concurrent.Service$$Lambda$267/1610290296.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$489(Unknown Source)
	at javafx.concurrent.Service$$Lambda$265/1250858972.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[07.04.15 1:30:46 AM] aok.coc.launcher.BotLauncher loop INFO: Waiting for dc checker to wake me up... 
</pre>

Base screenshot from Bluestack window:
![bs](https://cloud.githubusercontent.com/assets/4902584/8504728/15ee8150-21f4-11e5-8128-3f09396c4fa4.png)

**Comment by norecha** [comment]
it should have an image in bug folder, can you attach that

**Comment by ashishmverma1** [comment]
Looking in the bug folder, I see it captured my desktop background instead of the loot area. Could be an issue with me pressing Ctrl or using my mouse while the bot was in action?

**Comment by norecha** [comment]
Those shouldn't be an issue. Only thing I can think of is you moving the 
window or putting something else in front. Nothing else makes sense.

**Comment by ashishmverma1** [comment]
Well that ain't possible since I keep the Bluestack window on a secondary monitor  and it stays untouched.

I'll just wait and see if the same issue happens again.

**Comment by Mondster** [comment]
Looks like there's indeed a bug on the troops count, the bar always not deploy when there is no king in the loot. 

[07.04.15 10:21:25 AM] INFO: StateAttack 
[07.04.15 10:21:27 AM] INFO: [gold: 269602, elixir: 148246, de: 255] 
[07.04.15 10:21:31 AM] INFO: [Troop count: [0, 89, 0, 0]] 
[07.04.15 10:21:36 AM] INFO: StateAttack 
[07.04.15 10:21:38 AM] INFO: [gold: 93651, elixir: 83643, de: 739] 
[07.04.15 10:21:42 AM] INFO: [Troop count: [0, 89, 0, 0]] 
[07.04.15 10:21:45 AM] INFO: StateAttack 
[07.04.15 10:21:48 AM] INFO: [gold: 45142, elixir: 69836, de: 487] 
[07.04.15 10:21:52 AM] INFO: [Troop count: [0, 89, 0, 0]] 
[07.04.15 10:21:56 AM] INFO: StateAttack 
[07.04.15 10:21:58 AM] INFO: [gold: 36339, elixir: 45919, de: 609] 
[07.04.15 10:22:02 AM] INFO: [Troop count: [0, 89, 0, 0]] 
[07.04.15 10:22:06 AM] INFO: StateAttack 
[07.04.15 10:22:08 AM] INFO: [gold: 205791, elixir: 134196, de: 777] 
[07.04.15 10:22:12 AM] INFO: [Troop count: [0, 89, 0, 0]] 
![04-jul-15 10-26-31 am](https://cloud.githubusercontent.com/assets/13143891/8506123/79966b44-2237-11e5-93c9-f6e336e51fec.png)
![04-jul-15 10-26-50 am](https://cloud.githubusercontent.com/assets/13143891/8506122/7995cacc-2237-11e5-8256-1e42d8e6b113.png)

**Comment by 1-Click-Dev** [comment]
Same problem with ashishmverma, I used in a virtual machine, untouched, nothing on the screen, only pokubot and bluestack screen. but I see same error often.
